version: "3.9"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  task-service:
    build: ./backend/task-service
    ports:
      - "4000:4000"
    depends_on:
      - mongo
      - rabbitmq

  notification-service:
    build: ./backend/notification-service
    ports:
      - "5050:5050"
    depends_on:
      - rabbitmq

  api-gateway:
    build: ./backend/api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - task-service
      - notification-service
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true

  frontend:
    build: ./frontend
    ports:
      - "8080:3000"
    depends_on:
      - api-gateway
      
